### ISSUE TITLE
Epson L366

### ISSUE THREAD

**Issue by Derad6709** [Zedeldi/epson-printer-snmp#4]
Unfortunately, I didn't understand how to modify models.json to make it work with other printers, but I can provide log file from wicreset...
[application.log](https://github.com/Zedeldi/epson-printer-snmp/files/14972344/application.log)

**Comment by Zedeldi** [comment]
Thanks! I'll try to work through the log and add your model to the list :)

**Comment by Zedeldi** [comment]
Initial support added for Epson L366 with 12acfb568e757b34d08d2b68be87ed865ec87165.
Unfortunately, I am unable to test this, but please let me know if there are any issues :smiley:
